apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres-db-chart.fullname" . }}
  namespace: {{ .Values.namespace | default "" }}
spec:
  serviceName: {{ .Values.containerName }}-service
  selector:
    matchLabels:
      {{- include "postgres-db-chart.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "postgres-db-chart.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.containerName }}
          image: {{ .Values.image }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | default "" | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}
      volumes:
        {{- toYaml .Values.volumes | default "" | nindent 8 }}