apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gin-album-app-project
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: gin-album-app
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: true
  sourceRepos:
  - '*'