apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gin-album-app  # Change to your application name
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://quay.io/cbennett
    targetRevision: "v1.0.2"
    chart: gin-album-app-chart
    helm:
      values: |
        replicaCount: 3
  destination:
    server: https://kubernetes.default.svc
    namespace: gin-argo-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true