apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default .Values.default.namespace }}
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    app: {{ .Values.namespace | default .Values.default.namespace }}
spec: {}