kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-same-namespace
  namespace: {{ .Values.namespace | default .Values.default.namespace }}
spec:
  podSelector: {}
  ingress:
  - from:
    - podSelector: {}