apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-except-openshift
  namespace: {{ .Values.namespace | default .Values.defaultNamespace }}
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchNames:
        - openshift-system
        - openshift-logging
        - openshift-monitoring
        - default
    - podSelector: {}
  egress:
  - to:
    - namespaceSelector:
        matchNames:
        - openshift-system
        - openshift-logging
        - openshift-monitoring
        - default
    - podSelector: {}
