apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.default.resourceQuotaName }}
  namespace: {{ .Values.namespace | default .Values.default.namespace }}
spec:
  hard:
    pods: {{ .Values.podCount | default .Values.default.podCount }}
    requests.cpu: {{ .Values.cpuRequest | default .Values.default.cpuRequest }}
    limits.cpu: {{ .Values.cpuLimit | default .Values.default.cpuLimit }}
    requests.memory: {{ .Values.memoryRequest | default .Values.default.memoryRequest }}
    limits.memory: {{ .Values.memoryLimit | default .Values.default.memoryLimit }}