apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitops-access
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
