apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-resourcequota-creator
rules:
- apiGroups: [""] # Core API group for resourcequotas
  resources: ["resourcequotas"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"] # Add other verbs if needed (get, list, watch, update, patch, delete are common for management)