apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-db-chart.fullname" . }}
  namespace: {{ .Values.namespace | default "" }}
  labels:
    {{- include "postgres-db-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "postgres-db-chart.selectorLabels" . | nindent 4 }}
