apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-todo-app-chart
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/col1985/argocd-sample-apps.git
        revision: HEAD
        directories:
          # here it will read the paths under the app
          # umbrella chart and the subpaths
          - path: charts/todo-app/*/*
  template:
    metadata:
      namespace: openshift-gitops
      # you can use the path strings with / delimiter as variables
      name: "todo-app-{{path.basename}}"
    spec:
      project: default
      source:
        helm:
          # specify different values file based on directories variables
          valueFiles:
            - "env/{{path.basename}}/values.yaml"
            - "values.yaml"
        path: charts/todo-app
        repoURL: https://github.com/col1985/argocd-sample-apps.git
        targetRevision: HEAD
      syncPolicy:
        syncOptions:
        - ApplyOutOfSyncOnly=true
      destination:
        # specify different destinations
        namespace: "todo-app-{{path.basename}}"
        server: https://kubernetes.default.svc